In [ ]:
# 1. What is a Python library? Why do we use Python libraries?
# Answer:

"""
A Python library is a collection of modules and functions that provide specific functionalities, such as mathematical operations,
data manipulation, or machine learning. Libraries help in reusing code and simplify complex tasks by providing pre-written functions.
 Examples include NumPy, Pandas, and TensorFlow.
"""


In [ ]:
# 2. What is the difference between Numpy array and List?
# Answer:

"""
- NumPy Array: Fixed-size, homogeneous data structure with efficient memory and performance for numerical operations.
- Python List: Dynamic-size, heterogeneous data structure that can store different types of elements but is slower for numerical
operations compared to NumPy arrays.
"""


In [1]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)


Shape: (3, 4)
Size: 12
Dimensions: 2


In [2]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = arr[0]
print(first_row)


[1 2 3 4]


In [3]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

element = arr[2, 3]  # 3rd row (index 2), 4th column (index 3)
print(element)


12


In [4]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

odd_elements = arr[:, 1::2]  # Extract elements from odd columns (index 1 and 3)
print(odd_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [5]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
# Answer:

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.31985161 0.27201436 0.98131653]
 [0.25313779 0.24951713 0.13619022]
 [0.03665906 0.19597122 0.63526187]]


In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?

"""
- np.random.rand: Generates random numbers from a uniform distribution between 0 and 1.
- np.random.randn: Generates random numbers from a standard normal distribution (mean = 0, variance = 1).
"""


In [6]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

new_arr = arr[:, np.newaxis, :]
print(new_arr.shape)  # This will add a new axis (dimension)


(3, 1, 4)


In [7]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

transposed_arr = arr.T
print(transposed_arr)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
# 11. Consider the following matrix:
# Matrix A: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
# Matrix B: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
# Perform the following operation using Python:
# 1. Index wise multiplication
# 2. Matrix multiplication
# 3. Add both the matrices
# 4. Subtract matrix B from A
# 5. Divide Matrix B by A

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_mult = A * B
print("Index wise multiplication:\n", index_wise_mult)

# 2. Matrix multiplication
matrix_mult = np.dot(A, B.T)  # Transpose B to match dimensions
print("Matrix multiplication:\n", matrix_mult)

# 3. Add both the matrices
matrix_add = A + B
print("Addition:\n", matrix_add)

# 4. Subtract matrix B from A
matrix_sub = A - B
print("Subtraction:\n", matrix_sub)

# 5. Divide Matrix B by A
matrix_div = B / A
print("Division:\n", matrix_div)


Index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
# Answer:

"""
The function `np.ndarray.byteswap()` can be used to swap the byte order of an array in NumPy.
"""


In [ ]:
# 13. What is the significance of the np.linalg.inv function?
# Answer:

"""
The `np.linalg.inv()` function computes the inverse of a given square matrix. It is significant in solving linear algebra problems, such as finding solutions to systems of linear equations.
"""


In [ ]:
# 14. What does the np.reshape function do, and how is it used?
# Answer:

"""
The `np.reshape()` function changes the shape of a given array without changing its data. It is used to alter the dimensions of an array, for example, converting a 1D array into a 2D array.
Example:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
"""


In [ ]:
# 15. What is broadcasting in Numpy?
# Answer:

"""
Broadcasting in NumPy refers to the automatic expansion of smaller arrays so that they match the shape of larger arrays during operations like addition, multiplication, etc. It simplifies operations on arrays of different shapes.
"""
